version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - run: sudo apt-get -y -qq install awscli
      - checkout
      - run: npm install
      - run: npm run fetchdata
      - run: npm run build
      - deploy:
          name: Deploy to s3
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws sts get-caller-identity
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              aws s3 sync public s3://gtfs.org/ --delete
            fi
workflows:
  version: 2
  commit:
    jobs:
      - build
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
                - production
    jobs:
      - build
